import { sqliteTable, text, integer, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { relations } from 'drizzle-orm';
import { createId } from '@paralleldrive/cuid2';

// Users table - Better Auth compatible
export const users = sqliteTable('users', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name'),
  email: text('email').notNull().unique(),
  emailVerified: integer('emailVerified', { mode: 'boolean' }).default(false).notNull(),
  image: text('image'),
  password: text('password'), // hashed password (bcryptjs)
  role: text('role', { enum: ['user', 'admin'] }).default('user').notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  premiumUntil: integer('premiumUntil', { mode: 'timestamp' }), // null = no premium
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Session table - Better Auth compatible
export const sessions = sqliteTable('sessions', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  userId: text('userId').notNull().references(() => users.id, { onDelete: 'cascade' }),
  expiresAt: integer('expiresAt', { mode: 'timestamp' }).notNull(),
  token: text('token').notNull().unique(),
  ipAddress: text('ipAddress'),
  userAgent: text('userAgent'),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Account table - Better Auth compatible (for OAuth providers)
export const accounts = sqliteTable('accounts', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  userId: text('userId').notNull().references(() => users.id, { onDelete: 'cascade' }),
  accountId: text('accountId').notNull(), // Provider-specific account ID
  providerId: text('providerId').notNull(), // Provider identifier (e.g., 'google', 'github')
  accessToken: text('accessToken'),
  refreshToken: text('refreshToken'),
  idToken: text('idToken'),
  accessTokenExpiresAt: integer('accessTokenExpiresAt', { mode: 'timestamp' }),
  refreshTokenExpiresAt: integer('refreshTokenExpiresAt', { mode: 'timestamp' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Verification tokens (for email verification if needed later)
export const verificationTokens = sqliteTable('verificationTokens', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  identifier: text('identifier').notNull(),
  token: text('token').notNull().unique(),
  expiresAt: integer('expiresAt', { mode: 'timestamp' }).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Products table
export const products = sqliteTable('products', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description').notNull(),
  price: integer('price').notNull(), // Price in cents
  currency: text('currency').default('USD').notNull(),
  imageUrl: text('imageUrl'),
  imageFileId: text('imageFileId'),
  imageProvider: text('imageProvider'),
  fileKey: text('fileKey').notNull(), // R2 object key
  fileName: text('fileName').notNull(),
  fileSize: integer('fileSize'), // in bytes
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Purchases table
export const purchases = sqliteTable('purchases', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  userId: text('userId').references(() => users.id, { onDelete: 'set null' }),
  productId: text('productId').notNull().references(() => products.id),
  purchaseCode: text('purchaseCode').notNull().unique(), // Unique code for registration
  email: text('email').notNull(), // Email where purchase code was sent

  // Payment provider info (generic for multi-provider support)
  paymentProvider: text('paymentProvider'), // 'mercadopago', 'stripe', 'paypal', etc.
  externalPaymentId: text('externalPaymentId').unique(), // Provider's payment ID
  externalOrderId: text('externalOrderId'), // Provider's order ID
  providerStatus: text('providerStatus'), // Provider-specific status
  providerStatusDetail: text('providerStatusDetail'), // Provider-specific status detail
  checkoutUrl: text('checkoutUrl'), // Checkout URL generated by provider

  amount: integer('amount').notNull(), // Amount paid in cents
  currency: text('currency').default('USD').notNull(),

  // Status tracking
  status: text('status', {
    enum: ['initialized', 'pending', 'completed', 'refunded', 'failed']
  }).default('initialized').notNull(),

  // Discount fields
  couponId: text('couponId'),
  offerId: text('offerId'),
  discountSource: text('discountSource', { enum: ['coupon', 'offer'] }),
  discountAmount: integer('discountAmount').default(0).notNull(), // Discount in cents
  originalAmount: integer('originalAmount'), // Original price before discount

  // Registration tracking
  usedForRegistration: integer('usedForRegistration', { mode: 'boolean' }).default(false).notNull(),
  registrationUsedAt: integer('registrationUsedAt', { mode: 'timestamp' }),

  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Download links table
export const downloadLinks = sqliteTable('downloadLinks', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  purchaseId: text('purchaseId').notNull().references(() => purchases.id, { onDelete: 'cascade' }),
  userId: text('userId').references(() => users.id, { onDelete: 'cascade' }),
  productId: text('productId').notNull().references(() => products.id),

  token: text('token').notNull().unique(), // Unique token for the download link
  expiresAt: integer('expiresAt', { mode: 'timestamp' }).notNull(),

  downloadCount: integer('downloadCount').default(0).notNull(),
  maxDownloads: integer('maxDownloads').default(5).notNull(),

  lastDownloadedAt: integer('lastDownloadedAt', { mode: 'timestamp' }),
  ipAddress: text('ipAddress'),
  userAgent: text('userAgent'),

  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Site links table (global links for Linktree-style page)
export const siteLinks = sqliteTable('siteLinks', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  title: text('title').notNull(),
  url: text('url').notNull(),
  icon: text('icon').notNull(), // emoji string OR Lucide icon name
  iconType: text('iconType', { enum: ['emoji', 'lucide', 'simple-icons'] }).notNull().default('emoji'),
  linkType: text('linkType', { enum: ['social', 'custom'] }).notNull().default('custom'),
  order: integer('order').notNull().default(0), // For drag-and-drop ordering
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  clickCount: integer('clickCount').default(0).notNull(), // Analytics
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Newsletter subscribers table
export const newsletterSubscribers = sqliteTable('newsletterSubscribers', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  email: text('email').notNull().unique(),
  name: text('name'),
  phone: text('phone'),
  countryCode: text('countryCode', { enum: ['CO', 'US', 'MX'] }),
  status: text('status', { enum: ['active', 'unsubscribed'] }).default('active').notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  unsubscribedAt: integer('unsubscribedAt', { mode: 'timestamp' }),
  ipAddress: text('ipAddress'),
  userAgent: text('userAgent'),
});

// Blog categories table
export const blogCategories = sqliteTable('blogCategories', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  order: integer('order').default(0).notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Blogs table
export const blogs = sqliteTable('blogs', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  excerpt: text('excerpt'),
  content: text('content').notNull(), // HTML from TipTap editor
  coverImage: text('coverImage'), // ImageKit URL
  categoryId: text('categoryId').references(() => blogCategories.id, { onDelete: 'set null' }),
  isPublished: integer('isPublished', { mode: 'boolean' }).default(false).notNull(),
  isPremium: integer('isPremium', { mode: 'boolean' }).default(false).notNull(),
  publishedAt: integer('publishedAt', { mode: 'timestamp' }),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  purchases: many(purchases),
  downloadLinks: many(downloadLinks),
  accounts: many(accounts),
  sessions: many(sessions)
}));

export const productsRelations = relations(products, ({ many }) => ({
  purchases: many(purchases),
  downloadLinks: many(downloadLinks)
}));

export const purchasesRelations = relations(purchases, ({ one, many }) => ({
  user: one(users, {
    fields: [purchases.userId],
    references: [users.id]
  }),
  product: one(products, {
    fields: [purchases.productId],
    references: [products.id]
  }),
  downloadLinks: many(downloadLinks)
}));

export const downloadLinksRelations = relations(downloadLinks, ({ one }) => ({
  purchase: one(purchases, {
    fields: [downloadLinks.purchaseId],
    references: [purchases.id]
  }),
  user: one(users, {
    fields: [downloadLinks.userId],
    references: [users.id]
  }),
  product: one(products, {
    fields: [downloadLinks.productId],
    references: [products.id]
  })
}));

export const blogCategoriesRelations = relations(blogCategories, ({ many }) => ({
  blogs: many(blogs)
}));

export const blogsRelations = relations(blogs, ({ one }) => ({
  category: one(blogCategories, {
    fields: [blogs.categoryId],
    references: [blogCategories.id]
  })
}));

// Referral categories table
export const referralCategories = sqliteTable('referralCategories', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  order: integer('order').default(0).notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Referral/Affiliate links table
export const referralLinks = sqliteTable('referralLinks', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(), // URL: /r/[slug]
  description: text('description'),
  destinationUrl: text('destinationUrl').notNull(),
  image: text('image'),
  categoryId: text('categoryId').references(() => referralCategories.id, { onDelete: 'set null' }),

  // UTM params (appended to destination URL)
  utmSource: text('utmSource'),
  utmMedium: text('utmMedium'),
  utmCampaign: text('utmCampaign'),
  utmTerm: text('utmTerm'),
  utmContent: text('utmContent'),

  // Tracking aggregated stats
  clickCount: integer('clickCount').default(0).notNull(),
  lastClickAt: integer('lastClickAt', { mode: 'timestamp' }),

  order: integer('order').default(0).notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Referral clicks tracking table
export const referralClicks = sqliteTable('referralClicks', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  linkId: text('linkId').notNull().references(() => referralLinks.id, { onDelete: 'cascade' }),
  country: text('country'), // CF-IPCountry header
  userAgent: text('userAgent'),
  referer: text('referer'),
  ipAddress: text('ipAddress'),
  incomingUtmSource: text('incomingUtmSource'),
  incomingUtmMedium: text('incomingUtmMedium'),
  incomingUtmCampaign: text('incomingUtmCampaign'),
  clickedAt: integer('clickedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Referral relations
export const referralCategoriesRelations = relations(referralCategories, ({ many }) => ({
  links: many(referralLinks)
}));

export const referralLinksRelations = relations(referralLinks, ({ one, many }) => ({
  category: one(referralCategories, {
    fields: [referralLinks.categoryId],
    references: [referralCategories.id]
  }),
  clicks: many(referralClicks)
}));

export const referralClicksRelations = relations(referralClicks, ({ one }) => ({
  link: one(referralLinks, {
    fields: [referralClicks.linkId],
    references: [referralLinks.id]
  })
}));

// Coupons table
export const coupons = sqliteTable('coupons', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  code: text('code').notNull().unique(), // Unique code (e.g., VERANO20)
  name: text('name').notNull(), // Descriptive name
  description: text('description'),

  // Discount type
  discountType: text('discountType', { enum: ['percentage', 'fixed'] }).notNull(),
  discountValue: integer('discountValue').notNull(), // Percentage (0-100) or cents

  // Restrictions
  minPurchaseAmount: integer('minPurchaseAmount'), // Minimum amount in cents
  maxDiscountAmount: integer('maxDiscountAmount'), // Maximum discount cap in cents

  // Usage limits
  usageLimit: integer('usageLimit'), // Total usage limit (null = unlimited)
  usageCount: integer('usageCount').default(0).notNull(), // Current usage count
  usageLimitPerUser: integer('usageLimitPerUser'), // Per user/email limit (null = unlimited)

  // Specific products (null = all products)
  productIds: text('productIds'), // JSON array of IDs, null = applies to all

  // Validity period
  startsAt: integer('startsAt', { mode: 'timestamp' }),
  expiresAt: integer('expiresAt', { mode: 'timestamp' }),

  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Offers table (automatic promotions)
export const offers = sqliteTable('offers', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(), // e.g., "Black Friday 2024"
  description: text('description'),

  // Discount type
  discountType: text('discountType', { enum: ['percentage', 'fixed'] }).notNull(),
  discountValue: integer('discountValue').notNull(),

  // Restrictions
  minPurchaseAmount: integer('minPurchaseAmount'),
  maxDiscountAmount: integer('maxDiscountAmount'),

  // Usage limits
  usageLimit: integer('usageLimit'), // Total usage limit (null = unlimited)
  usageCount: integer('usageCount').default(0).notNull(), // Current usage count
  usageLimitPerUser: integer('usageLimitPerUser'), // Per user limit (null = unlimited)

  // Specific products
  productIds: text('productIds'), // JSON array, null = all

  // Scheduling (optional - null means always active)
  startsAt: integer('startsAt', { mode: 'timestamp' }),
  expiresAt: integer('expiresAt', { mode: 'timestamp' }),

  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Offer usages tracking table
export const offerUsages = sqliteTable('offerUsages', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  offerId: text('offerId').notNull().references(() => offers.id, { onDelete: 'cascade' }),
  purchaseId: text('purchaseId').notNull().references(() => purchases.id, { onDelete: 'cascade' }),
  userId: text('userId').references(() => users.id, { onDelete: 'set null' }),
  email: text('email').notNull(),
  discountApplied: integer('discountApplied').notNull(),
  usedAt: integer('usedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Coupon usages tracking table
export const couponUsages = sqliteTable('couponUsages', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  couponId: text('couponId').notNull().references(() => coupons.id, { onDelete: 'cascade' }),
  purchaseId: text('purchaseId').notNull().references(() => purchases.id, { onDelete: 'cascade' }),
  userId: text('userId').references(() => users.id, { onDelete: 'set null' }),
  email: text('email').notNull(), // Buyer's email
  discountApplied: integer('discountApplied').notNull(), // Discount applied in cents
  usedAt: integer('usedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Site settings table (key-value store)
export const siteSettings = sqliteTable('siteSettings', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  key: text('key').notNull().unique(),
  value: text('value').notNull(),
  type: text('type', { enum: ['string', 'number', 'boolean'] }).notNull().default('string'),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Template configurations table (per-template key-value store)
export const templateConfigs = sqliteTable('templateConfigs', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  templateId: text('templateId').notNull(), // 'jeyla', 'minimal', etc.
  key: text('key').notNull(), // 'primaryColor', 'heroProductId', etc.
  value: text('value').notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
}, (table) => ({
  templateKeyIdx: uniqueIndex('template_key_idx').on(table.templateId, table.key),
}));

// Coupon relations
export const couponsRelations = relations(coupons, ({ many }) => ({
  usages: many(couponUsages)
}));

export const couponUsagesRelations = relations(couponUsages, ({ one }) => ({
  coupon: one(coupons, {
    fields: [couponUsages.couponId],
    references: [coupons.id]
  }),
  purchase: one(purchases, {
    fields: [couponUsages.purchaseId],
    references: [purchases.id]
  }),
  user: one(users, {
    fields: [couponUsages.userId],
    references: [users.id]
  })
}));

// ==================== RECIPE MODULE ====================

// Recipe categories table
export const recipeCategories = sqliteTable('recipeCategories', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  order: integer('order').default(0).notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Recipes table
export const recipes = sqliteTable('recipes', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  imageUrl: text('imageUrl'),
  estimatedTime: integer('estimatedTime').notNull(), // in minutes
  calories: integer('calories'), // per serving (editable)
  servings: integer('servings').notNull().default(1), // base servings for calculations
  difficulty: text('difficulty', { enum: ['easy', 'medium', 'hard'] }).default('medium').notNull(),
  categoryId: text('categoryId').references(() => recipeCategories.id, { onDelete: 'set null' }),
  isPublished: integer('isPublished', { mode: 'boolean' }).default(false).notNull(),
  isPremium: integer('isPremium', { mode: 'boolean' }).default(false).notNull(),
  publishedAt: integer('publishedAt', { mode: 'timestamp' }),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Recipe preparations table (e.g., "For the pasta", "For the chicken")
export const recipePreparations = sqliteTable('recipePreparations', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  recipeId: text('recipeId').notNull().references(() => recipes.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  order: integer('order').default(0).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Recipe steps table
export const recipeSteps = sqliteTable('recipeSteps', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  preparationId: text('preparationId').notNull().references(() => recipePreparations.id, { onDelete: 'cascade' }),
  instruction: text('instruction').notNull(),
  order: integer('order').default(0).notNull(),
  timerSeconds: integer('timerSeconds'), // null if no timer needed
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Recipe preparation ingredients table (ingredients per preparation)
export const recipePreparationIngredients = sqliteTable('recipePreparationIngredients', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  preparationId: text('preparationId').notNull().references(() => recipePreparations.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  quantity: integer('quantity').notNull(), // multiplied by 100 for decimals (e.g., 250 = 2.5)
  unit: text('unit').notNull(), // g, kg, ml, l, unit, tbsp, tsp, cup, pinch
  calories: integer('calories'), // calories for this ingredient amount (optional)
  order: integer('order').default(0).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Recipe relations
export const recipeCategoriesRelations = relations(recipeCategories, ({ many }) => ({
  recipes: many(recipes)
}));

export const recipesRelations = relations(recipes, ({ one, many }) => ({
  category: one(recipeCategories, {
    fields: [recipes.categoryId],
    references: [recipeCategories.id]
  }),
  preparations: many(recipePreparations)
}));

export const recipePreparationsRelations = relations(recipePreparations, ({ one, many }) => ({
  recipe: one(recipes, {
    fields: [recipePreparations.recipeId],
    references: [recipes.id]
  }),
  steps: many(recipeSteps),
  ingredients: many(recipePreparationIngredients)
}));

export const recipeStepsRelations = relations(recipeSteps, ({ one }) => ({
  preparation: one(recipePreparations, {
    fields: [recipeSteps.preparationId],
    references: [recipePreparations.id]
  })
}));

export const recipePreparationIngredientsRelations = relations(recipePreparationIngredients, ({ one }) => ({
  preparation: one(recipePreparations, {
    fields: [recipePreparationIngredients.preparationId],
    references: [recipePreparations.id]
  })
}));

// ==================== PEOPLE MODULE ====================

// Person categories table
export const personCategories = sqliteTable('personCategories', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  order: integer('order').default(0).notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Person titles table (professional titles)
export const personTitles = sqliteTable('personTitles', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  order: integer('order').default(0).notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// Skills table
export const skills = sqliteTable('skills', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  color: text('color'), // Hex color for badge display
  order: integer('order').default(0).notNull(),
  isActive: integer('isActive', { mode: 'boolean' }).default(true).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// People table
export const people = sqliteTable('people', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  titleId: text('titleId').references(() => personTitles.id, { onDelete: 'set null' }),
  shortBio: text('shortBio'), // Short description for cards
  bio: text('bio'), // Full bio HTML from TipTap editor
  avatarUrl: text('avatarUrl'), // ImageKit URL
  avatarFileId: text('avatarFileId'), // ImageKit file ID for deletion
  categoryId: text('categoryId').references(() => personCategories.id, { onDelete: 'set null' }),

  // Contact fields with visibility
  email: text('email'),
  emailIsPublic: integer('emailIsPublic', { mode: 'boolean' }).default(false).notNull(),
  phone: text('phone'),
  phoneIsPublic: integer('phoneIsPublic', { mode: 'boolean' }).default(false).notNull(),
  whatsapp: text('whatsapp'), // Full number with country code
  whatsappIsPublic: integer('whatsappIsPublic', { mode: 'boolean' }).default(false).notNull(),

  // Social links
  website: text('website'),
  instagram: text('instagram'),

  // Status
  order: integer('order').default(0).notNull(),
  isPublished: integer('isPublished', { mode: 'boolean' }).default(false).notNull(),
  publishedAt: integer('publishedAt', { mode: 'timestamp' }),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// People-Skills junction table (many-to-many)
export const peopleSkills = sqliteTable('peopleSkills', {
  id: text('id').primaryKey().$defaultFn(() => createId()),
  personId: text('personId').notNull().references(() => people.id, { onDelete: 'cascade' }),
  skillId: text('skillId').notNull().references(() => skills.id, { onDelete: 'cascade' }),
  order: integer('order').default(0).notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp' }).$defaultFn(() => new Date()).notNull(),
});

// People relations
export const personCategoriesRelations = relations(personCategories, ({ many }) => ({
  people: many(people)
}));

export const personTitlesRelations = relations(personTitles, ({ many }) => ({
  people: many(people)
}));

export const skillsRelations = relations(skills, ({ many }) => ({
  peopleSkills: many(peopleSkills)
}));

export const peopleRelations = relations(people, ({ one, many }) => ({
  category: one(personCategories, {
    fields: [people.categoryId],
    references: [personCategories.id]
  }),
  title: one(personTitles, {
    fields: [people.titleId],
    references: [personTitles.id]
  }),
  skills: many(peopleSkills)
}));

export const peopleSkillsRelations = relations(peopleSkills, ({ one }) => ({
  person: one(people, {
    fields: [peopleSkills.personId],
    references: [people.id]
  }),
  skill: one(skills, {
    fields: [peopleSkills.skillId],
    references: [skills.id]
  })
}));
